# Generated by Django 3.1 on 2020-09-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0007_worknamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=100, unique=True)),
                ('project_title', models.CharField(max_length=100, unique=True)),
                ('project_code', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('tender_value', models.IntegerField()),
                ('tender_fees', models.IntegerField()),
                ('tender_bit_value', models.IntegerField()),
                ('EMD_amount_value', models.IntegerField()),
                ('tender_auction_date', models.DateField()),
                ('tender_publish_date', models.DateField()),
                ('project_description', models.TextField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender', to='masters.companymodel')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.companymodel')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.customermodel')),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.workcategorymodel')),
            ],
        ),
    ]
