# Generated by Django 3.1 on 2020-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_auto_20201001_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderdetails',
            name='project_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenderdetails',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenderdetails',
            name='tender_id',
            field=models.CharField(max_length=100),
        ),
    ]
