# Generated by Django 3.1 on 2020-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_departmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
