# Generated by Django 3.1 on 2020-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_workrolemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpecializationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspecialization', models.CharField(max_length=100)),
            ],
        ),
    ]
