# Generated by Django 3.1 on 2020-09-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_workspecializationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=100)),
                ('workrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.workrolemodel')),
                ('workspecialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.workspecializationmodel')),
            ],
        ),
    ]
